databases:
  - name: api
    region: singapore
    plan: free
    databaseName: api
    user: django_user

services:
  - type: web
    name: api
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: "python -m gunicorn mark.asgi:application -k uvicorn.workers.UvicornWorker"
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true